name: Changelog
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master
      - develop
jobs:
  build:
    name: Check Changelog Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: CHANGELOG.md # default `CHANGELOG.adoc`
          noChangelogLabel: my custom label # default `no changelog`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
