name: Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: install
      working-directory: .
      run: yarn install

    - name: build
      working-directory: .
      run: yarn docs:build

    - name: upload build
      uses: actions/upload-artifact@v4
      with:
          name: build
          path: ./docs/.vuepress/dist


  # links:
  #   name: Test Links
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download math result for job 1
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: build
  #     - shell: bash
  #       run: ls -la build

  #     - name: Link Checker
  #       id: lc
  #       uses: peter-evans/link-checker@v1
  #       with:
  #         args: -d build -x "enterprise\.sven\.com\/*|sven\.io" -r *

  #     - name: Create Issue From File
  #       uses: peter-evans/create-issue-from-file@v2
  #       with:
  #         title: Link Checker Report
  #         content-filepath: ./link-checker/out.md
  #         labels: report, automated issue

  #     - name: Fail if there were link errors
  #       run: exit ${{ steps.lc.outputs.exit_code }}
